### ISSUE TITLE
Installation failled 

### ISSUE THREAD

**Issue by clemaitre58** [scikit-cycling/scikit-cycling#35]
10:25 $ cd ~/Downloads/

pi@raspberrypi:~/Downloads$ pip install git+https://github.com/scikit-cycling/scikit-cycling.git

Collecting git+https://github.com/scikit-cycling/scikit-cycling.git
  Cloning https://github.com/scikit-cycling/scikit-cycling.git to /tmp/pip-_7ciik-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named Cython.Compiler.Main
    skcycling
    Processing skcycling/extraction/_power_profile.pyx
    Traceback (most recent call last):
      File "/tmp/pip-_7ciik-build/tools/cythonize.py", line 198, in <module>
        main(root_dir_arg)
      File "/tmp/pip-_7ciik-build/tools/cythonize.py", line 190, in main
        check_and_cythonize(root_dir)
      File "/tmp/pip-_7ciik-build/tools/cythonize.py", line 182, in check_and_cythonize
        cythonize_if_unchanged(cur_dir, cython_file, gen_file, hashes)
      File "/tmp/pip-_7ciik-build/tools/cythonize.py", line 156, in cythonize_if_unchanged
        cythonize(full_cython_path, full_gen_file_path)
      File "/tmp/pip-_7ciik-build/tools/cythonize.py", line 85, in cythonize
        raise Exception('Cythonizing %s failed' % cython_file)
    Exception: Cythonizing skcycling/extraction/_power_profile.pyx failed
    Cythonizing sources
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-_7ciik-build/setup.py", line 142, in <module>
        setup_package()
      File "/tmp/pip-_7ciik-build/setup.py", line 113, in setup_package
        generate_cython(PACKAGE_NAME)
      File "/tmp/pip-_7ciik-build/setup.py", line 79, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-_7ciik-build/

**Comment by glemaitre** [comment]
you don't have cython installed.
What I wanted to try is 

```
pip install numpy Cython
pip install scikit-cycling
```
